### ISSUE TITLE
404 错误

### ISSUE THREAD

**Issue by Accpet** [chimojiacai/grafana-wecaht-alert#4]
[root@ip-172-31-225-87 grafana-wecaht-alert]# ./wechat-alert 
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /                         --> main.GetSendCount (3 handlers)
[GIN-debug] POST   /send                     --> main.SendMsg (3 handlers)
json: cannot unmarshal number into Go struct field Hook.orgId of type string
[GIN] 2022/01/18 - 08:55:17 | 400 |     208.094µs |   172.31.225.87 | POST     "/send"
json: cannot unmarshal number into Go struct field Hook.orgId of type string
[GIN] 2022/01/18 - 08:55:19 | 400 |      79.057µs |   172.31.225.87 | POST     "/send"
[GIN] 2022/01/18 - 08:56:48 | 404 |         1.9µs |   172.31.225.87 | PUT      "/send?key=d64a0caa-bf62-4958-8f8e-08af39761"
[GIN] 2022/01/18 - 08:56:50 | 404 |       1.984µs |   172.31.225.87 | PUT      "/send?key=d64a0caa-bf62-4958-8f8e-08af39761"
[GIN] 2022/01/18 - 08:56:51 | 404 |       1.799µs |   172.31.225.87 | PUT      "/send?key=d64a0caa-bf62-4958-8f8e-08af39761"
[GIN] 2022/01/18 - 08:56:52 | 404 |        1.96µs |   172.31.225.87 | PUT      "/send?key=d64a0caa-bf62-4958-8f8e-08af39761"
[GIN] 2022/01/18 - 08:56:52 | 404 |       1.714µs |   172.31.225.87 | PUT      "/send?key=d64a0caa-bf62-4958-8f8e-08af39761"
[GIN] 2022/01/18 - 08:56:52 | 404 |       1.837µs |   172.31.225.87 | PUT      "/send?key=d64a0caa-bf62-4958-8f8e-08af39761"
[GIN] 2022/01/18 - 08:56:52 | 404 |       2.038µs |   172.31.225.87 | PUT      "/send?key=d64a0caa-bf62-4958-8f8e-08af397"
[GIN] 2022/01/18 - 08:57:00 | 404 |       1.727µs |   172.31.225.87 | PUT      "/send?key=d64a0caa-bf62-4958-8f8e-08af39761"
[GIN] 2022/01/18 - 08:57:00 | 404 |       1.873µs |   172.31.225.87 | PUT      "/send?key=d64a0caa-bf62-4958-8f8e-08af39761"
[GIN] 2022/01/18 - 08:57:01 | 404 |       2.018µs |   172.31.225.87 | PUT      "/send?key=d64a0caa-bf62-4958-8f8e-08af39761"
[GIN] 2022/01/18 - 08:57:01 | 404 |       1.933µs |   172.31.225.87 | PUT      "/send?key=d64a0caa-bf62-4958-8f8e-08af39761"

**Comment by chimojiacai** [comment]
send方法是post，我看你日志里请求方法用的put。
